seed: 42
out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: gineconv-zinc
  entity: floraj-oregon-state-university
  name: test
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_edge:
  enable: True
  harmonic: resistance
  normalize: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: default
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 80  # `gt.dim_hidden` must match `gnn.dim_inner`
  layer_type: gineconv
  residual: False
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.001 # 0.0002
  max_epoch: 1000 # 10000
  scheduler: polynomial_with_warmup
